services:
  postgres:
    image: postgres:16
    container_name: sinasc-postgres
    restart: always
    environment:
      POSTGRES_USER: sinasc
      POSTGRES_PASSWORD: sinasc123
      POSTGRES_DB: sinasc_access
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: